config/routes.rb
Rails.application.routes.draw do
  resources :passengers
  resources :routes
  resources :vehicles
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :passengers_routes
  has_many :routes, :through => :passengers_routes

  validates :name, presence: true,  :on => :create
  validates :number_id, presence: true, :on => :create
  validates :sex, presence: true, :on => :create
  validates :cellphone_number, presence: true, :on => :create
end

app/models/passengers_route.rb
class Passengers_route < ApplicationRecord
  belongs_to :route
  belongs_to :passenger
end

app/models/route.rb
class Route < ApplicationRecord
  has_many :passengers_routes
  has_many :passengers, :through => :passengers_routes
  belongs_to :vehicle
  validates :name, presence: true,  :on => :create
  validates :description, presence: true, :on => :create
  validates :category, presence: true, :on => :create
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :routes
  validates :color, presence: true
  validates :year, presence: true

  validates :license_plate, length: { is: 6 }, presence: true, uniqueness: true
  validates_format_of :license_plate, :with => /\A(ABC|DFG)((\w+))\Z/i, :on => :create

  before_create :add_category

  def add_category()
    if self.license_plate.include? "ABC"
      self.category = "1"
    else
      if self.license_plate.include? "DFG"
           self.category = "2"
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_params
      params.require(:passenger).permit(:name, :number_id, :sex, :cellphone_number)
    end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:name, :description, :type)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:license_plate, :color, :year)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
      <%= value %>
    </div>
<% end %>

<% if current_user %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to 'Login', new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/passengers/_form.html.erb
<%= form_for(passenger) do |f| %>
  <% if passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :number_id %>
    <%= f.text_field :number_id %>
  </div>

  <div class="field">
    <%= f.label :sex %>
    <%= f.text_field :sex %>
  </div>

  <div class="field">
    <%= f.label :cellphone_number %>
    <%= f.text_field :cellphone_number %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

app/views/passengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Passengers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number</th>
      <th>Sex</th>
      <th>Cellphone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.name %></td>
        <td><%= passenger.number_id %></td>
        <td><%= passenger.sex %></td>
        <td><%= passenger.cellphone_number %></td>
        <td><%= link_to 'Show', passenger %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger', new_passenger_path %>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form', passenger: @passenger %>

<%= link_to 'Back', passengers_path %>

app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @passenger.number_id %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @passenger.sex %>
</p>

<p>
  <strong>Cellphone number:</strong>
  <%= @passenger.cellphone_number %>
</p>

<%= link_to 'Edit', edit_passenger_path(@passenger) %> |
<%= link_to 'Back', passengers_path %>

app/views/routes/_form.html.erb
<%= form_for(route) do |f| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<% if !current_user %>
    <script type="text/javascript">
      window.location.href="/"  // put your correct path in a string here
    </script>
<% end %>

<h1>Routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= route.description %></td>
        <td><%= route.category %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @route.description %>
</p>

<p>
  <strong>Type:</strong>
  <%= @route.type %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

app/views/static_pages/home.html.erb
<h1>Esta es la pagina de inicio</h1>
<% if current_user %>
    <script type="text/javascript">
      window.location.href="/routes"  // put your correct path in a string here
    </script>
<% end %>

app/views/vehicles/_form.html.erb
<%= form_for(vehicle) do |f| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :license_plate %>
    <%= f.text_field :license_plate %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.text_field :year %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
    <tr>
      <th>License plate</th>
      <th>Color</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.license_plate %></td>
        <td><%= vehicle.color %></td>
        <td><%= vehicle.year %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>License plate:</strong>
  <%= @vehicle.license_plate %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicle.color %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>